// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SysReqProto.proto

package com.qs.game.socket.client.msg;

public final class SysReqProto {
  private SysReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SysReqProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.SysReqProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>required int32 type = 1;</code>
     */
    boolean hasType();
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>required int32 type = 1;</code>
     */
    int getType();

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>required string reqMsg = 2;</code>
     */
    boolean hasReqMsg();
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>required string reqMsg = 2;</code>
     */
    String getReqMsg();
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>required string reqMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getReqMsgBytes();

    /**
     * <pre>
     * 来自哪个用户id
     * </pre>
     *
     * <code>optional string fromId = 3;</code>
     */
    boolean hasFromId();
    /**
     * <pre>
     * 来自哪个用户id
     * </pre>
     *
     * <code>optional string fromId = 3;</code>
     */
    String getFromId();
    /**
     * <pre>
     * 来自哪个用户id
     * </pre>
     *
     * <code>optional string fromId = 3;</code>
     */
    com.google.protobuf.ByteString
        getFromIdBytes();

    /**
     * <pre>
     * 去往哪个用户id
     * </pre>
     *
     * <code>optional string toId = 4;</code>
     */
    boolean hasToId();
    /**
     * <pre>
     * 去往哪个用户id
     * </pre>
     *
     * <code>optional string toId = 4;</code>
     */
    String getToId();
    /**
     * <pre>
     * 去往哪个用户id
     * </pre>
     *
     * <code>optional string toId = 4;</code>
     */
    com.google.protobuf.ByteString
        getToIdBytes();

    /**
     * <pre>
     * 去往哪个服务器ip
     * </pre>
     *
     * <code>optional string toServerHost = 5;</code>
     */
    boolean hasToServerHost();
    /**
     * <pre>
     * 去往哪个服务器ip
     * </pre>
     *
     * <code>optional string toServerHost = 5;</code>
     */
    String getToServerHost();
    /**
     * <pre>
     * 去往哪个服务器ip
     * </pre>
     *
     * <code>optional string toServerHost = 5;</code>
     */
    com.google.protobuf.ByteString
        getToServerHostBytes();

    /**
     * <pre>
     * 去往哪个服务器的端口
     * </pre>
     *
     * <code>optional int32 toServerPort = 6;</code>
     */
    boolean hasToServerPort();
    /**
     * <pre>
     * 去往哪个服务器的端口
     * </pre>
     *
     * <code>optional int32 toServerPort = 6;</code>
     */
    int getToServerPort();

    /**
     * <pre>
     * 来自哪个服务器ip
     * </pre>
     *
     * <code>optional string fromServerHost = 7;</code>
     */
    boolean hasFromServerHost();
    /**
     * <pre>
     * 来自哪个服务器ip
     * </pre>
     *
     * <code>optional string fromServerHost = 7;</code>
     */
    String getFromServerHost();
    /**
     * <pre>
     * 来自哪个服务器ip
     * </pre>
     *
     * <code>optional string fromServerHost = 7;</code>
     */
    com.google.protobuf.ByteString
        getFromServerHostBytes();

    /**
     * <pre>
     * 来自哪个服务器的端口
     * </pre>
     *
     * <code>optional int32 fromServerPort = 8;</code>
     */
    boolean hasFromServerPort();
    /**
     * <pre>
     * 来自哪个服务器的端口
     * </pre>
     *
     * <code>optional int32 fromServerPort = 8;</code>
     */
    int getFromServerPort();
  }
  /**
   * Protobuf type {@code protocol.SysReqProtocol}
   */
  public  static final class SysReqProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.SysReqProtocol)
      SysReqProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SysReqProtocol.newBuilder() to construct.
    private SysReqProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SysReqProtocol() {
      type_ = 0;
      reqMsg_ = "";
      fromId_ = "";
      toId_ = "";
      toServerHost_ = "";
      toServerPort_ = 0;
      fromServerHost_ = "";
      fromServerPort_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SysReqProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              reqMsg_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              fromId_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              toId_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              toServerHost_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              toServerPort_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              fromServerHost_ = bs;
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              fromServerPort_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SysReqProto.internal_static_protocol_SysReqProtocol_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SysReqProto.internal_static_protocol_SysReqProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SysReqProtocol.class, Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>required int32 type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>required int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int REQMSG_FIELD_NUMBER = 2;
    private volatile Object reqMsg_;
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>required string reqMsg = 2;</code>
     */
    public boolean hasReqMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>required string reqMsg = 2;</code>
     */
    public String getReqMsg() {
      Object ref = reqMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reqMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>required string reqMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReqMsgBytes() {
      Object ref = reqMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reqMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMID_FIELD_NUMBER = 3;
    private volatile Object fromId_;
    /**
     * <pre>
     * 来自哪个用户id
     * </pre>
     *
     * <code>optional string fromId = 3;</code>
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 来自哪个用户id
     * </pre>
     *
     * <code>optional string fromId = 3;</code>
     */
    public String getFromId() {
      Object ref = fromId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 来自哪个用户id
     * </pre>
     *
     * <code>optional string fromId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      Object ref = fromId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOID_FIELD_NUMBER = 4;
    private volatile Object toId_;
    /**
     * <pre>
     * 去往哪个用户id
     * </pre>
     *
     * <code>optional string toId = 4;</code>
     */
    public boolean hasToId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 去往哪个用户id
     * </pre>
     *
     * <code>optional string toId = 4;</code>
     */
    public String getToId() {
      Object ref = toId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 去往哪个用户id
     * </pre>
     *
     * <code>optional string toId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getToIdBytes() {
      Object ref = toId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        toId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOSERVERHOST_FIELD_NUMBER = 5;
    private volatile Object toServerHost_;
    /**
     * <pre>
     * 去往哪个服务器ip
     * </pre>
     *
     * <code>optional string toServerHost = 5;</code>
     */
    public boolean hasToServerHost() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * 去往哪个服务器ip
     * </pre>
     *
     * <code>optional string toServerHost = 5;</code>
     */
    public String getToServerHost() {
      Object ref = toServerHost_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toServerHost_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 去往哪个服务器ip
     * </pre>
     *
     * <code>optional string toServerHost = 5;</code>
     */
    public com.google.protobuf.ByteString
        getToServerHostBytes() {
      Object ref = toServerHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        toServerHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOSERVERPORT_FIELD_NUMBER = 6;
    private int toServerPort_;
    /**
     * <pre>
     * 去往哪个服务器的端口
     * </pre>
     *
     * <code>optional int32 toServerPort = 6;</code>
     */
    public boolean hasToServerPort() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * 去往哪个服务器的端口
     * </pre>
     *
     * <code>optional int32 toServerPort = 6;</code>
     */
    public int getToServerPort() {
      return toServerPort_;
    }

    public static final int FROMSERVERHOST_FIELD_NUMBER = 7;
    private volatile Object fromServerHost_;
    /**
     * <pre>
     * 来自哪个服务器ip
     * </pre>
     *
     * <code>optional string fromServerHost = 7;</code>
     */
    public boolean hasFromServerHost() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * 来自哪个服务器ip
     * </pre>
     *
     * <code>optional string fromServerHost = 7;</code>
     */
    public String getFromServerHost() {
      Object ref = fromServerHost_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromServerHost_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 来自哪个服务器ip
     * </pre>
     *
     * <code>optional string fromServerHost = 7;</code>
     */
    public com.google.protobuf.ByteString
        getFromServerHostBytes() {
      Object ref = fromServerHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromServerHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMSERVERPORT_FIELD_NUMBER = 8;
    private int fromServerPort_;
    /**
     * <pre>
     * 来自哪个服务器的端口
     * </pre>
     *
     * <code>optional int32 fromServerPort = 8;</code>
     */
    public boolean hasFromServerPort() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     * 来自哪个服务器的端口
     * </pre>
     *
     * <code>optional int32 fromServerPort = 8;</code>
     */
    public int getFromServerPort() {
      return fromServerPort_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, reqMsg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fromId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, toId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, toServerHost_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, toServerPort_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, fromServerHost_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, fromServerPort_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, reqMsg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fromId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, toId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, toServerHost_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, toServerPort_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, fromServerHost_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, fromServerPort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SysReqProtocol)) {
        return super.equals(obj);
      }
      SysReqProtocol other = (SysReqProtocol) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && (getType()
            == other.getType());
      }
      result = result && (hasReqMsg() == other.hasReqMsg());
      if (hasReqMsg()) {
        result = result && getReqMsg()
            .equals(other.getReqMsg());
      }
      result = result && (hasFromId() == other.hasFromId());
      if (hasFromId()) {
        result = result && getFromId()
            .equals(other.getFromId());
      }
      result = result && (hasToId() == other.hasToId());
      if (hasToId()) {
        result = result && getToId()
            .equals(other.getToId());
      }
      result = result && (hasToServerHost() == other.hasToServerHost());
      if (hasToServerHost()) {
        result = result && getToServerHost()
            .equals(other.getToServerHost());
      }
      result = result && (hasToServerPort() == other.hasToServerPort());
      if (hasToServerPort()) {
        result = result && (getToServerPort()
            == other.getToServerPort());
      }
      result = result && (hasFromServerHost() == other.hasFromServerHost());
      if (hasFromServerHost()) {
        result = result && getFromServerHost()
            .equals(other.getFromServerHost());
      }
      result = result && (hasFromServerPort() == other.hasFromServerPort());
      if (hasFromServerPort()) {
        result = result && (getFromServerPort()
            == other.getFromServerPort());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      if (hasReqMsg()) {
        hash = (37 * hash) + REQMSG_FIELD_NUMBER;
        hash = (53 * hash) + getReqMsg().hashCode();
      }
      if (hasFromId()) {
        hash = (37 * hash) + FROMID_FIELD_NUMBER;
        hash = (53 * hash) + getFromId().hashCode();
      }
      if (hasToId()) {
        hash = (37 * hash) + TOID_FIELD_NUMBER;
        hash = (53 * hash) + getToId().hashCode();
      }
      if (hasToServerHost()) {
        hash = (37 * hash) + TOSERVERHOST_FIELD_NUMBER;
        hash = (53 * hash) + getToServerHost().hashCode();
      }
      if (hasToServerPort()) {
        hash = (37 * hash) + TOSERVERPORT_FIELD_NUMBER;
        hash = (53 * hash) + getToServerPort();
      }
      if (hasFromServerHost()) {
        hash = (37 * hash) + FROMSERVERHOST_FIELD_NUMBER;
        hash = (53 * hash) + getFromServerHost().hashCode();
      }
      if (hasFromServerPort()) {
        hash = (37 * hash) + FROMSERVERPORT_FIELD_NUMBER;
        hash = (53 * hash) + getFromServerPort();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SysReqProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SysReqProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SysReqProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SysReqProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SysReqProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SysReqProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SysReqProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SysReqProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SysReqProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SysReqProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SysReqProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SysReqProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SysReqProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.SysReqProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.SysReqProtocol)
        SysReqProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SysReqProto.internal_static_protocol_SysReqProtocol_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SysReqProto.internal_static_protocol_SysReqProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SysReqProtocol.class, Builder.class);
      }

      // Construct using com.qs.game.protocol.SysReqProto.SysReqProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        reqMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        fromId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        toId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        toServerHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        toServerPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        fromServerHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        fromServerPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SysReqProto.internal_static_protocol_SysReqProtocol_descriptor;
      }

      @Override
      public SysReqProtocol getDefaultInstanceForType() {
        return SysReqProtocol.getDefaultInstance();
      }

      @Override
      public SysReqProtocol build() {
        SysReqProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SysReqProtocol buildPartial() {
        SysReqProtocol result = new SysReqProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reqMsg_ = reqMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fromId_ = fromId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.toId_ = toId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.toServerHost_ = toServerHost_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.toServerPort_ = toServerPort_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.fromServerHost_ = fromServerHost_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.fromServerPort_ = fromServerPort_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SysReqProtocol) {
          return mergeFrom((SysReqProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SysReqProtocol other) {
        if (other == SysReqProtocol.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasReqMsg()) {
          bitField0_ |= 0x00000002;
          reqMsg_ = other.reqMsg_;
          onChanged();
        }
        if (other.hasFromId()) {
          bitField0_ |= 0x00000004;
          fromId_ = other.fromId_;
          onChanged();
        }
        if (other.hasToId()) {
          bitField0_ |= 0x00000008;
          toId_ = other.toId_;
          onChanged();
        }
        if (other.hasToServerHost()) {
          bitField0_ |= 0x00000010;
          toServerHost_ = other.toServerHost_;
          onChanged();
        }
        if (other.hasToServerPort()) {
          setToServerPort(other.getToServerPort());
        }
        if (other.hasFromServerHost()) {
          bitField0_ |= 0x00000040;
          fromServerHost_ = other.fromServerHost_;
          onChanged();
        }
        if (other.hasFromServerPort()) {
          setFromServerPort(other.getFromServerPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasReqMsg()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SysReqProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SysReqProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>required int32 type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>required int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>required int32 type = 1;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>required int32 type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private Object reqMsg_ = "";
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>required string reqMsg = 2;</code>
       */
      public boolean hasReqMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>required string reqMsg = 2;</code>
       */
      public String getReqMsg() {
        Object ref = reqMsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            reqMsg_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>required string reqMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReqMsgBytes() {
        Object ref = reqMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          reqMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>required string reqMsg = 2;</code>
       */
      public Builder setReqMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reqMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>required string reqMsg = 2;</code>
       */
      public Builder clearReqMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reqMsg_ = getDefaultInstance().getReqMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>required string reqMsg = 2;</code>
       */
      public Builder setReqMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reqMsg_ = value;
        onChanged();
        return this;
      }

      private Object fromId_ = "";
      /**
       * <pre>
       * 来自哪个用户id
       * </pre>
       *
       * <code>optional string fromId = 3;</code>
       */
      public boolean hasFromId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 来自哪个用户id
       * </pre>
       *
       * <code>optional string fromId = 3;</code>
       */
      public String getFromId() {
        Object ref = fromId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fromId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 来自哪个用户id
       * </pre>
       *
       * <code>optional string fromId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFromIdBytes() {
        Object ref = fromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 来自哪个用户id
       * </pre>
       *
       * <code>optional string fromId = 3;</code>
       */
      public Builder setFromId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来自哪个用户id
       * </pre>
       *
       * <code>optional string fromId = 3;</code>
       */
      public Builder clearFromId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fromId_ = getDefaultInstance().getFromId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来自哪个用户id
       * </pre>
       *
       * <code>optional string fromId = 3;</code>
       */
      public Builder setFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fromId_ = value;
        onChanged();
        return this;
      }

      private Object toId_ = "";
      /**
       * <pre>
       * 去往哪个用户id
       * </pre>
       *
       * <code>optional string toId = 4;</code>
       */
      public boolean hasToId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 去往哪个用户id
       * </pre>
       *
       * <code>optional string toId = 4;</code>
       */
      public String getToId() {
        Object ref = toId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            toId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 去往哪个用户id
       * </pre>
       *
       * <code>optional string toId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getToIdBytes() {
        Object ref = toId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          toId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 去往哪个用户id
       * </pre>
       *
       * <code>optional string toId = 4;</code>
       */
      public Builder setToId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 去往哪个用户id
       * </pre>
       *
       * <code>optional string toId = 4;</code>
       */
      public Builder clearToId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        toId_ = getDefaultInstance().getToId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 去往哪个用户id
       * </pre>
       *
       * <code>optional string toId = 4;</code>
       */
      public Builder setToIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        toId_ = value;
        onChanged();
        return this;
      }

      private Object toServerHost_ = "";
      /**
       * <pre>
       * 去往哪个服务器ip
       * </pre>
       *
       * <code>optional string toServerHost = 5;</code>
       */
      public boolean hasToServerHost() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * 去往哪个服务器ip
       * </pre>
       *
       * <code>optional string toServerHost = 5;</code>
       */
      public String getToServerHost() {
        Object ref = toServerHost_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            toServerHost_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 去往哪个服务器ip
       * </pre>
       *
       * <code>optional string toServerHost = 5;</code>
       */
      public com.google.protobuf.ByteString
          getToServerHostBytes() {
        Object ref = toServerHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          toServerHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 去往哪个服务器ip
       * </pre>
       *
       * <code>optional string toServerHost = 5;</code>
       */
      public Builder setToServerHost(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        toServerHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 去往哪个服务器ip
       * </pre>
       *
       * <code>optional string toServerHost = 5;</code>
       */
      public Builder clearToServerHost() {
        bitField0_ = (bitField0_ & ~0x00000010);
        toServerHost_ = getDefaultInstance().getToServerHost();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 去往哪个服务器ip
       * </pre>
       *
       * <code>optional string toServerHost = 5;</code>
       */
      public Builder setToServerHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        toServerHost_ = value;
        onChanged();
        return this;
      }

      private int toServerPort_ ;
      /**
       * <pre>
       * 去往哪个服务器的端口
       * </pre>
       *
       * <code>optional int32 toServerPort = 6;</code>
       */
      public boolean hasToServerPort() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       * 去往哪个服务器的端口
       * </pre>
       *
       * <code>optional int32 toServerPort = 6;</code>
       */
      public int getToServerPort() {
        return toServerPort_;
      }
      /**
       * <pre>
       * 去往哪个服务器的端口
       * </pre>
       *
       * <code>optional int32 toServerPort = 6;</code>
       */
      public Builder setToServerPort(int value) {
        bitField0_ |= 0x00000020;
        toServerPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 去往哪个服务器的端口
       * </pre>
       *
       * <code>optional int32 toServerPort = 6;</code>
       */
      public Builder clearToServerPort() {
        bitField0_ = (bitField0_ & ~0x00000020);
        toServerPort_ = 0;
        onChanged();
        return this;
      }

      private Object fromServerHost_ = "";
      /**
       * <pre>
       * 来自哪个服务器ip
       * </pre>
       *
       * <code>optional string fromServerHost = 7;</code>
       */
      public boolean hasFromServerHost() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * 来自哪个服务器ip
       * </pre>
       *
       * <code>optional string fromServerHost = 7;</code>
       */
      public String getFromServerHost() {
        Object ref = fromServerHost_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fromServerHost_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 来自哪个服务器ip
       * </pre>
       *
       * <code>optional string fromServerHost = 7;</code>
       */
      public com.google.protobuf.ByteString
          getFromServerHostBytes() {
        Object ref = fromServerHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fromServerHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 来自哪个服务器ip
       * </pre>
       *
       * <code>optional string fromServerHost = 7;</code>
       */
      public Builder setFromServerHost(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        fromServerHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来自哪个服务器ip
       * </pre>
       *
       * <code>optional string fromServerHost = 7;</code>
       */
      public Builder clearFromServerHost() {
        bitField0_ = (bitField0_ & ~0x00000040);
        fromServerHost_ = getDefaultInstance().getFromServerHost();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来自哪个服务器ip
       * </pre>
       *
       * <code>optional string fromServerHost = 7;</code>
       */
      public Builder setFromServerHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        fromServerHost_ = value;
        onChanged();
        return this;
      }

      private int fromServerPort_ ;
      /**
       * <pre>
       * 来自哪个服务器的端口
       * </pre>
       *
       * <code>optional int32 fromServerPort = 8;</code>
       */
      public boolean hasFromServerPort() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       * 来自哪个服务器的端口
       * </pre>
       *
       * <code>optional int32 fromServerPort = 8;</code>
       */
      public int getFromServerPort() {
        return fromServerPort_;
      }
      /**
       * <pre>
       * 来自哪个服务器的端口
       * </pre>
       *
       * <code>optional int32 fromServerPort = 8;</code>
       */
      public Builder setFromServerPort(int value) {
        bitField0_ |= 0x00000080;
        fromServerPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来自哪个服务器的端口
       * </pre>
       *
       * <code>optional int32 fromServerPort = 8;</code>
       */
      public Builder clearFromServerPort() {
        bitField0_ = (bitField0_ & ~0x00000080);
        fromServerPort_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.SysReqProtocol)
    }

    // @@protoc_insertion_point(class_scope:protocol.SysReqProtocol)
    private static final SysReqProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SysReqProtocol();
    }

    public static SysReqProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<SysReqProtocol>
        PARSER = new com.google.protobuf.AbstractParser<SysReqProtocol>() {
      @Override
      public SysReqProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SysReqProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SysReqProtocol> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SysReqProtocol> getParserForType() {
      return PARSER;
    }

    @Override
    public SysReqProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SysReqProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_SysReqProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021SysReqProto.proto\022\010protocol\"\250\001\n\016SysReq" +
      "Protocol\022\014\n\004type\030\001 \002(\005\022\016\n\006reqMsg\030\002 \002(\t\022\016" +
      "\n\006fromId\030\003 \001(\t\022\014\n\004toId\030\004 \001(\t\022\024\n\014toServer" +
      "Host\030\005 \001(\t\022\024\n\014toServerPort\030\006 \001(\005\022\026\n\016from" +
      "ServerHost\030\007 \001(\t\022\026\n\016fromServerPort\030\010 \001(\005" +
      "B#\n\024com.qs.game.protocolB\013SysReqProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_SysReqProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_SysReqProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_SysReqProtocol_descriptor,
        new String[] { "Type", "ReqMsg", "FromId", "ToId", "ToServerHost", "ToServerPort", "FromServerHost", "FromServerPort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
